<?
$PERM["user"]["8"]="W";
$PERM["search"]["8"]="W";
$PERM["products"]["8"]="W";
$PERM["partner"]["8"]="W";
$PERM["news"]["8"]="W";
$PERM["news"]["12"]="W";
$PERM["contacts"]["8"]="W";
$PERM["company"]["8"]="W";
$PERM["index.php"]["8"]="W";
$PERM["index.php"]["12"]="W";
$PERM["forum"]["8"]="W";
$PERM["forum"]["12"]="W";
$PERM["blogs"]["8"]="W";
$PERM["blogs"]["12"]="W";
$PERM["/"]["*"]="R";
?>